<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 3,
                'title' => 'ReadMe Note 12 pro',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 7,
                'short_description' => '8-128 variant',
                'source_url' => null,
                'source_price' => null,
                'price' => 10.00,
                'cross_price' => 12.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/YPKgkHq7Jx1seKDIGm8QhaG3MMPyreDLHlKP6HD5.jpg',
                'image_gal' => null,
                'created_at' => '2025-09-21 00:35:42',
                'updated_at' => '2025-09-21 00:45:49',
            ],
            [
                'id' => 5,
                'title' => 'Pc',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 6,
                'short_description' => '5600g processor',
                'source_url' => null,
                'source_price' => null,
                'price' => 20.00,
                'cross_price' => 22.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/gYWKyWSYi7bJ7MGMhpKsB3D8tvNbjZvLcyk0gKsR.webp',
                'image_gal' => null,
                'created_at' => '2025-09-21 04:03:33',
                'updated_at' => '2025-09-21 07:23:22',
            ],
            [
                'id' => 6,
                'title' => 'Mini Pc',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 9,
                'short_description' => 'asdfgg',
                'source_url' => null,
                'source_price' => null,
                'price' => 10.00,
                'cross_price' => 12.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/KXOyLG9QYffxpQQuScv1QFF7ynfvglGIneFiZWUq.jpg',
                'image_gal' => null,
                'created_at' => '2025-09-21 04:29:04',
                'updated_at' => '2025-09-21 04:29:04',
            ],
            [
                'id' => 7,
                'title' => 'Redme Note 10 Pro',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 7,
                'short_description' => 'dffs',
                'source_url' => null,
                'source_price' => null,
                'price' => 1000.00,
                'cross_price' => 1200.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/lelwN3vJtyPOPq2VJITgpUsakjgtPMstP9leivR1.jpg',
                'image_gal' => null,
                'created_at' => '2025-09-21 04:29:44',
                'updated_at' => '2025-09-21 04:29:44',
            ],
            [
                'id' => 8,
                'title' => 'Redmi Note 12 Pro',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 7,
                'short_description' => '8-256',
                'source_url' => null,
                'source_price' => null,
                'price' => 2000.00,
                'cross_price' => 2000.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/1RaC7pA5FIPJZySmbfV55i6W92PKiODx6ke0kcaJ.jpg',
                'image_gal' => null,
                'created_at' => '2025-09-21 04:30:31',
                'updated_at' => '2025-09-21 04:30:31',
            ],
            [
                'id' => 9,
                'title' => 'Macbook Air',
                'description' => null,
                'sizes' => null,
                'colors' => null,
                'user_id' => 2,
                'category_id' => 10,
                'short_description' => '8-256',
                'source_url' => null,
                'source_price' => null,
                'price' => 5000.00,
                'cross_price' => 5500.00,
                'profit' => null,
                'status' => 1,
                'is_featured' => 'yes',
                'image' => 'products/kbtVf42lc4Epc8ylRVBp3Q5xq8sMgbn1l8Qai7TB.jpg',
                'image_gal' => null,
                'created_at' => '2025-09-21 04:31:31',
                'updated_at' => '2025-09-21 04:31:31',
            ],
        
        ]);
    }
}
